[build]
  publish = "build"
  command = "pip install -r requirements.txt && python build.py"

[build.environment]
  PYTHON_VERSION = "3.8"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200